# Generated by Django 5.0.8 on 2024-09-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatzone2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_accepted',
        ),
    ]
