# Generated by Django 5.0.8 on 2024-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketitem', '0003_order_card_cvv_order_card_expiry_order_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
