# Generated by Django 5.0.8 on 2024-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketitem', '0004_order_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='item',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon'), ('unavailable', 'Currently Unavailable')], default='available', max_length=20),
        ),
    ]
